# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(1000, 790)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 790))
        MainWindow.setMaximumSize(QtCore.QSize(1000, 790))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(85, 170, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        MainWindow.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setMouseTracking(False)
        MainWindow.setTabletTracking(False)
        MainWindow.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/tubiao.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_result = QtWidgets.QFrame(self.centralwidget)
        self.frame_result.setEnabled(False)
        self.frame_result.setGeometry(QtCore.QRect(29, 309, 941, 381))
        self.frame_result.setStyleSheet("background:rgb(255, 255, 255);\n"
"border:1px solid #aaa;")
        self.frame_result.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_result.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_result.setObjectName("frame_result")
        self.listWidget_result = QtWidgets.QListWidget(self.frame_result)
        self.listWidget_result.setGeometry(QtCore.QRect(0, 10, 941, 341))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.listWidget_result.setFont(font)
        self.listWidget_result.setAutoScrollMargin(10)
        self.listWidget_result.setObjectName("listWidget_result")
        self.frame_log = QtWidgets.QFrame(self.centralwidget)
        self.frame_log.setEnabled(False)
        self.frame_log.setGeometry(QtCore.QRect(30, 220, 940, 51))
        self.frame_log.setStyleSheet("background:rgb(255, 255, 255);\n"
"border:1px solid #aaa;")
        self.frame_log.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_log.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_log.setObjectName("frame_log")
        self.plainTextEdit_log = QtWidgets.QPlainTextEdit(self.frame_log)
        self.plainTextEdit_log.setGeometry(QtCore.QRect(10, 10, 921, 31))
        self.plainTextEdit_log.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.plainTextEdit_log.setAutoFillBackground(False)
        self.plainTextEdit_log.setStyleSheet("border:0px;")
        self.plainTextEdit_log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.plainTextEdit_log.setReadOnly(False)
        self.plainTextEdit_log.setObjectName("plainTextEdit_log")
        self.label_scanresult = QtWidgets.QLabel(self.centralwidget)
        self.label_scanresult.setEnabled(False)
        self.label_scanresult.setGeometry(QtCore.QRect(30, 290, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_scanresult.setFont(font)
        self.label_scanresult.setObjectName("label_scanresult")
        self.label_loginfo = QtWidgets.QLabel(self.centralwidget)
        self.label_loginfo.setEnabled(False)
        self.label_loginfo.setGeometry(QtCore.QRect(30, 200, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_loginfo.setFont(font)
        self.label_loginfo.setObjectName("label_loginfo")
        self.widget_option = QtWidgets.QWidget(self.centralwidget)
        self.widget_option.setGeometry(QtCore.QRect(30, 20, 940, 151))
        self.widget_option.setStyleSheet("border:1px solid #aaa;")
        self.widget_option.setObjectName("widget_option")
        self.label_target = QtWidgets.QLabel(self.widget_option)
        self.label_target.setEnabled(False)
        self.label_target.setGeometry(QtCore.QRect(10, 10, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_target.setFont(font)
        self.label_target.setStyleSheet("color:#000;border:0px;")
        self.label_target.setObjectName("label_target")
        self.lineEdit_target = QtWidgets.QLineEdit(self.widget_option)
        self.lineEdit_target.setEnabled(True)
        self.lineEdit_target.setGeometry(QtCore.QRect(60, 10, 551, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_target.setFont(font)
        self.lineEdit_target.setObjectName("lineEdit_target")
        self.pushButton_start = QtWidgets.QPushButton(self.widget_option)
        self.pushButton_start.setEnabled(True)
        self.pushButton_start.setGeometry(QtCore.QRect(630, 10, 93, 28))
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("border:2px solid #aaa;")
        self.pushButton_start.setObjectName("pushButton_start")
        self.pushButton_end = QtWidgets.QPushButton(self.widget_option)
        self.pushButton_end.setEnabled(False)
        self.pushButton_end.setGeometry(QtCore.QRect(830, 10, 93, 28))
        self.pushButton_end.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_end.setStyleSheet("border:2px solid #aaa;")
        self.pushButton_end.setObjectName("pushButton_end")
        self.label_speed = QtWidgets.QLabel(self.widget_option)
        self.label_speed.setGeometry(QtCore.QRect(10, 70, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_speed.setFont(font)
        self.label_speed.setStyleSheet("color:#000;border:0px;")
        self.label_speed.setObjectName("label_speed")
        self.comboBox_speed = QtWidgets.QComboBox(self.widget_option)
        self.comboBox_speed.setGeometry(QtCore.QRect(90, 70, 51, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_speed.setFont(font)
        self.comboBox_speed.setObjectName("comboBox_speed")
        self.comboBox_speed.addItem("")
        self.comboBox_speed.addItem("")
        self.comboBox_speed.addItem("")
        self.checkBox_php = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_php.setGeometry(QtCore.QRect(530, 60, 61, 19))
        self.checkBox_php.setStyleSheet("border:0px;")
        self.checkBox_php.setChecked(True)
        self.checkBox_php.setObjectName("checkBox_php")
        self.checkBox_asp = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_asp.setGeometry(QtCore.QRect(530, 90, 61, 19))
        self.checkBox_asp.setStyleSheet("border:0px;")
        self.checkBox_asp.setObjectName("checkBox_asp")
        self.checkBox_jsp = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_jsp.setGeometry(QtCore.QRect(700, 60, 61, 21))
        self.checkBox_jsp.setStyleSheet("border:0px;")
        self.checkBox_jsp.setObjectName("checkBox_jsp")
        self.checkBox_aspx = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_aspx.setGeometry(QtCore.QRect(530, 120, 71, 19))
        self.checkBox_aspx.setStyleSheet("border:0px;")
        self.checkBox_aspx.setObjectName("checkBox_aspx")
        self.checkBox_others = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_others.setGeometry(QtCore.QRect(700, 90, 91, 19))
        self.checkBox_others.setStyleSheet("border:0px;")
        self.checkBox_others.setChecked(True)
        self.checkBox_others.setObjectName("checkBox_others")
        self.checkBox_user_defined = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_user_defined.setGeometry(QtCore.QRect(700, 120, 151, 19))
        self.checkBox_user_defined.setStyleSheet("border:0px;")
        self.checkBox_user_defined.setChecked(True)
        self.checkBox_user_defined.setObjectName("checkBox_user_defined")
        self.label_php_num = QtWidgets.QLabel(self.widget_option)
        self.label_php_num.setGeometry(QtCore.QRect(600, 60, 61, 21))
        self.label_php_num.setStyleSheet("border:0px;")
        self.label_php_num.setObjectName("label_php_num")
        self.label_asp_num = QtWidgets.QLabel(self.widget_option)
        self.label_asp_num.setGeometry(QtCore.QRect(600, 90, 61, 21))
        self.label_asp_num.setStyleSheet("border:0px;")
        self.label_asp_num.setObjectName("label_asp_num")
        self.label_aspx_num = QtWidgets.QLabel(self.widget_option)
        self.label_aspx_num.setGeometry(QtCore.QRect(600, 120, 61, 21))
        self.label_aspx_num.setStyleSheet("border:0px;")
        self.label_aspx_num.setObjectName("label_aspx_num")
        self.label_jsp_num = QtWidgets.QLabel(self.widget_option)
        self.label_jsp_num.setGeometry(QtCore.QRect(860, 60, 51, 21))
        self.label_jsp_num.setStyleSheet("border:0px;")
        self.label_jsp_num.setObjectName("label_jsp_num")
        self.label_others_num = QtWidgets.QLabel(self.widget_option)
        self.label_others_num.setGeometry(QtCore.QRect(860, 90, 51, 21))
        self.label_others_num.setStyleSheet("border:0px;")
        self.label_others_num.setObjectName("label_others_num")
        self.label_user_defined_num = QtWidgets.QLabel(self.widget_option)
        self.label_user_defined_num.setGeometry(QtCore.QRect(860, 120, 51, 21))
        self.label_user_defined_num.setStyleSheet("border:0px;")
        self.label_user_defined_num.setObjectName("label_user_defined_num")
        self.label_delay = QtWidgets.QLabel(self.widget_option)
        self.label_delay.setGeometry(QtCore.QRect(10, 110, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_delay.setFont(font)
        self.label_delay.setStyleSheet("color:#000;border:0px;")
        self.label_delay.setObjectName("label_delay")
        self.timeEdit_delay = QtWidgets.QTimeEdit(self.widget_option)
        self.timeEdit_delay.setEnabled(False)
        self.timeEdit_delay.setGeometry(QtCore.QRect(90, 110, 51, 22))
        self.timeEdit_delay.setProperty("showGroupSeparator", False)
        self.timeEdit_delay.setDateTime(QtCore.QDateTime(QtCore.QDate(2000, 1, 1), QtCore.QTime(0, 0, 0)))
        self.timeEdit_delay.setTimeSpec(QtCore.Qt.LocalTime)
        self.timeEdit_delay.setObjectName("timeEdit_delay")
        self.checkBox_status_code_200 = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_status_code_200.setGeometry(QtCore.QRect(280, 60, 61, 21))
        self.checkBox_status_code_200.setStyleSheet("border:0px;")
        self.checkBox_status_code_200.setChecked(True)
        self.checkBox_status_code_200.setObjectName("checkBox_status_code_200")
        self.label_status_code = QtWidgets.QLabel(self.widget_option)
        self.label_status_code.setGeometry(QtCore.QRect(200, 60, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_status_code.setFont(font)
        self.label_status_code.setStyleSheet("color:#000;border:0px;")
        self.label_status_code.setObjectName("label_status_code")
        self.checkBox_status_code_403 = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_status_code_403.setGeometry(QtCore.QRect(350, 60, 61, 21))
        self.checkBox_status_code_403.setStyleSheet("border:0px;")
        self.checkBox_status_code_403.setObjectName("checkBox_status_code_403")
        self.checkBox_status_code_3XX = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_status_code_3XX.setGeometry(QtCore.QRect(280, 110, 61, 21))
        self.checkBox_status_code_3XX.setStyleSheet("border:0px;")
        self.checkBox_status_code_3XX.setObjectName("checkBox_status_code_3XX")
        self.checkBox_status_code_500 = QtWidgets.QCheckBox(self.widget_option)
        self.checkBox_status_code_500.setGeometry(QtCore.QRect(350, 110, 61, 21))
        self.checkBox_status_code_500.setStyleSheet("border:0px;")
        self.checkBox_status_code_500.setObjectName("checkBox_status_code_500")
        self.label_suffix = QtWidgets.QLabel(self.widget_option)
        self.label_suffix.setGeometry(QtCore.QRect(460, 60, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_suffix.setFont(font)
        self.label_suffix.setStyleSheet("color:#000;border:0px;")
        self.label_suffix.setObjectName("label_suffix")
        self.line_left = QtWidgets.QFrame(self.widget_option)
        self.line_left.setGeometry(QtCore.QRect(180, 54, 1, 85))
        self.line_left.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_left.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_left.setObjectName("line_left")
        self.line_right = QtWidgets.QFrame(self.widget_option)
        self.line_right.setGeometry(QtCore.QRect(440, 54, 1, 85))
        self.line_right.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_right.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_right.setObjectName("line_right")
        self.pushButton_stop = QtWidgets.QPushButton(self.widget_option)
        self.pushButton_stop.setEnabled(False)
        self.pushButton_stop.setGeometry(QtCore.QRect(730, 10, 93, 28))
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("border:2px solid #aaa;")
        self.pushButton_stop.setObjectName("pushButton_stop")
        self.checkBox_detail = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_detail.setGeometry(QtCore.QRect(880, 197, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.checkBox_detail.setFont(font)
        self.checkBox_detail.setStyleSheet("border:0px;")
        self.checkBox_detail.setObjectName("checkBox_detail")
        self.label_task_number = QtWidgets.QLabel(self.centralwidget)
        self.label_task_number.setEnabled(False)
        self.label_task_number.setGeometry(QtCore.QRect(30, 710, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_task_number.setFont(font)
        self.label_task_number.setObjectName("label_task_number")
        self.label_task_queue = QtWidgets.QLabel(self.centralwidget)
        self.label_task_queue.setEnabled(False)
        self.label_task_queue.setGeometry(QtCore.QRect(150, 710, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_task_queue.setFont(font)
        self.label_task_queue.setObjectName("label_task_queue")
        self.label_task_queue_val = QtWidgets.QLabel(self.centralwidget)
        self.label_task_queue_val.setGeometry(QtCore.QRect(220, 706, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_task_queue_val.setFont(font)
        self.label_task_queue_val.setStyleSheet("border:0px;")
        self.label_task_queue_val.setObjectName("label_task_queue_val")
        self.label_request_times = QtWidgets.QLabel(self.centralwidget)
        self.label_request_times.setEnabled(False)
        self.label_request_times.setGeometry(QtCore.QRect(290, 710, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_request_times.setFont(font)
        self.label_request_times.setObjectName("label_request_times")
        self.label_request_times_val = QtWidgets.QLabel(self.centralwidget)
        self.label_request_times_val.setGeometry(QtCore.QRect(360, 706, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_request_times_val.setFont(font)
        self.label_request_times_val.setStyleSheet("border:0px;")
        self.label_request_times_val.setObjectName("label_request_times_val")
        self.label_completed = QtWidgets.QLabel(self.centralwidget)
        self.label_completed.setEnabled(False)
        self.label_completed.setGeometry(QtCore.QRect(420, 710, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_completed.setFont(font)
        self.label_completed.setObjectName("label_completed")
        self.label_completed_val = QtWidgets.QLabel(self.centralwidget)
        self.label_completed_val.setGeometry(QtCore.QRect(490, 706, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_completed_val.setFont(font)
        self.label_completed_val.setStyleSheet("border:0px;")
        self.label_completed_val.setObjectName("label_completed_val")
        self.label_task_number_val = QtWidgets.QLabel(self.centralwidget)
        self.label_task_number_val.setGeometry(QtCore.QRect(100, 706, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_task_number_val.setFont(font)
        self.label_task_number_val.setStyleSheet("border:0px;")
        self.label_task_number_val.setObjectName("label_task_number_val")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setEnabled(False)
        self.label_status.setGeometry(QtCore.QRect(790, 710, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_status.setFont(font)
        self.label_status.setObjectName("label_status")
        self.label_status_value = QtWidgets.QLabel(self.centralwidget)
        self.label_status_value.setEnabled(False)
        self.label_status_value.setGeometry(QtCore.QRect(840, 710, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_status_value.setFont(font)
        self.label_status_value.setStyleSheet("color:#000")
        self.label_status_value.setObjectName("label_status_value")
        self.label_error_times = QtWidgets.QLabel(self.centralwidget)
        self.label_error_times.setEnabled(False)
        self.label_error_times.setGeometry(QtCore.QRect(560, 710, 72, 15))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_error_times.setFont(font)
        self.label_error_times.setObjectName("label_error_times")
        self.label_error_times_val = QtWidgets.QLabel(self.centralwidget)
        self.label_error_times_val.setGeometry(QtCore.QRect(630, 706, 61, 25))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_error_times_val.setFont(font)
        self.label_error_times_val.setStyleSheet("border:0px;")
        self.label_error_times_val.setObjectName("label_error_times_val")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 33))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menufile1 = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.menufile1.setFont(font)
        self.menufile1.setObjectName("menufile1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_setting = QtWidgets.QAction(MainWindow)
        self.action_setting.setCheckable(False)
        self.action_setting.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_setting.setFont(font)
        self.action_setting.setObjectName("action_setting")
        self.action_about = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_about.setFont(font)
        self.action_about.setObjectName("action_about")
        self.menufile1.addAction(self.action_setting)
        self.menufile1.addAction(self.action_about)
        self.menubar.addAction(self.menufile1.menuAction())

        self.retranslateUi(MainWindow)
        self.comboBox_speed.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WBS"))
        self.label_scanresult.setText(_translate("MainWindow", "扫描结果："))
        self.label_loginfo.setText(_translate("MainWindow", "Error Log："))
        self.label_target.setText(_translate("MainWindow", "目标："))
        self.pushButton_start.setText(_translate("MainWindow", "开始"))
        self.pushButton_end.setText(_translate("MainWindow", "结束"))
        self.label_speed.setText(_translate("MainWindow", "扫描速度："))
        self.comboBox_speed.setItemText(0, _translate("MainWindow", "低"))
        self.comboBox_speed.setItemText(1, _translate("MainWindow", "中"))
        self.comboBox_speed.setItemText(2, _translate("MainWindow", "高"))
        self.checkBox_php.setText(_translate("MainWindow", "PHP"))
        self.checkBox_asp.setText(_translate("MainWindow", "ASP"))
        self.checkBox_jsp.setText(_translate("MainWindow", "JSP"))
        self.checkBox_aspx.setText(_translate("MainWindow", "ASPX"))
        self.checkBox_others.setText(_translate("MainWindow", "Others"))
        self.checkBox_user_defined.setText(_translate("MainWindow", "User-Defined"))
        self.label_php_num.setText(_translate("MainWindow", "0"))
        self.label_asp_num.setText(_translate("MainWindow", "0"))
        self.label_aspx_num.setText(_translate("MainWindow", "0"))
        self.label_jsp_num.setText(_translate("MainWindow", "0"))
        self.label_others_num.setText(_translate("MainWindow", "0"))
        self.label_user_defined_num.setText(_translate("MainWindow", "0"))
        self.label_delay.setText(_translate("MainWindow", "设置延迟："))
        self.timeEdit_delay.setDisplayFormat(_translate("MainWindow", "mm"))
        self.checkBox_status_code_200.setText(_translate("MainWindow", "200"))
        self.label_status_code.setText(_translate("MainWindow", "状态码："))
        self.checkBox_status_code_403.setText(_translate("MainWindow", "403"))
        self.checkBox_status_code_3XX.setText(_translate("MainWindow", "3XX"))
        self.checkBox_status_code_500.setText(_translate("MainWindow", "500"))
        self.label_suffix.setText(_translate("MainWindow", "后缀："))
        self.pushButton_stop.setText(_translate("MainWindow", "暂停"))
        self.checkBox_detail.setText(_translate("MainWindow", "显示细节"))
        self.label_task_number.setText(_translate("MainWindow", "任务数量："))
        self.label_task_queue.setText(_translate("MainWindow", "任务队列:"))
        self.label_task_queue_val.setText(_translate("MainWindow", "0"))
        self.label_request_times.setText(_translate("MainWindow", "发送请求:"))
        self.label_request_times_val.setText(_translate("MainWindow", "0"))
        self.label_completed.setText(_translate("MainWindow", "完成请求:"))
        self.label_completed_val.setText(_translate("MainWindow", "0"))
        self.label_task_number_val.setText(_translate("MainWindow", "0"))
        self.label_status.setText(_translate("MainWindow", "状态："))
        self.label_status_value.setText(_translate("MainWindow", "准备"))
        self.label_error_times.setText(_translate("MainWindow", "失败次数："))
        self.label_error_times_val.setText(_translate("MainWindow", "0"))
        self.menufile1.setTitle(_translate("MainWindow", "文件"))
        self.action_setting.setText(_translate("MainWindow", "配置"))
        self.action_about.setText(_translate("MainWindow", "关于"))
